### ISSUE TITLE
Typo in the SCIM v2 Swagger file

### ISSUE THREAD

**Issue by LasneF** [gravitee-io/gravitee-docs#1103]
There is a typo here 
https://github.com/gravitee-io/gravitee-docs/blob/master/am/2.x/scim/swagger.yml#L599 

here 
```
 Member:
    type: object
    properties:
      value:
        type: string
        description: id attribute of a SCIM resource
      $ref:
        type: string
        description: The URI of a SCIM resource.
      display:
        trype: string
        description: A human-readable name for the member
```

the display type , trype vs type , that makes the spec wrong ( object vs string) , that creates wrong sample as well
