### ISSUE TITLE
Add information about how to configure notifier email

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/gravitee-docs#285]
https://docs.gravitee.io/ae/userguide_notifier_system_email.html

```
notifiers:
  email:
    enabled: true
    host: ${email.host}
    subject: ${email.subject}
    port: ${email.port}
    username: ${email.username}
    password: ${email.password}
#    starttls.enabled: false
#    ssl:
#      trustAll: false
#      keyStore:
#      keyStorePassword:
```
